<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function openlayersxyzplus_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_layers':
        return array('version' => 1);
      case 'openlayers_styles':
        return array('version' => 1);
    }
  }
}




/**
 * Implementation of openlayers_layer_type
 */
function openlayersxyzplus_openlayers_layer_types() {
  return array(
    'openlayers_layer_type_openlayersxyzplus' => array(
      'title' => t('Custom xyz map layer'),
      'description' => t('Custom xyz layer based on stock xyz layer'),
       'layer_type' => array(
        'path' => drupal_get_path('module', 'openlayersxyzplus') . '/includes/layer_types',
        'file' => 'openlayersxyzplus.inc',
        'class' => 'openlayers_layer_type_openlayersxyzplus',
        'parent' => 'openlayers_layer_type',
      ),
    ),
  );
}
